name: sequia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15
  - statsmodels=0.13.5
  - pmdarima=1.8.5
  - pandas=1.4.0
  - shapely=1.8.5
  - fiona=1.8.21
  - geopandas=0.9.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - openssl=3.1.0
  - earthengine-api==0.1.342
  - psycopg2==2.9.3

